### ISSUE TITLE
Grid layout icon

### ISSUE THREAD

**Issue by cd-slash** [CyCraft/pepicons#109]
### requested icon

Grid layout icon to complement the list icon
Would likely look very similar to the existing qr code icon (4 squares in a grid) but without the qr-code specific outline

### category suggestion

UI category

### search synonyms

grid, layout, UI element, squares, display as icons

**Comment by mesqueeb** [comment]
@harryowens what do you think
![image](https://user-images.githubusercontent.com/3253920/189252016-b8769b09-d9f4-4422-bfd3-fa9b67bfd234.jpeg)

**Comment by mesqueeb** [comment]
here's the SVGs, because it might take another while until they get actuall released as part of the library

![grid_cards_table_list_to-do_todo_items_sort_organise_organize_tasks_sheet_entries_register_directory_catalogue_inventory_index_checklist_table](https://user-images.githubusercontent.com/3253920/189252228-a918cd74-f5e7-4934-998f-a320a8e68a76.svg)

![grid_cards_table_list_to-do_todo_items_sort_organise_organize_tasks_sheet_entries_register_directory_catalogue_inventory_index_checklist_table](https://user-images.githubusercontent.com/3253920/189252236-97fc16e9-ef5f-48cc-b4a4-f605359a5195.svg)

**Comment by cd-slash** [comment]
Wow, that was quick! These look amazing, exactly what I had in mind 🙏🏻

**Comment by mesqueeb** [comment]
@harryowens released on latest v1.2.0
